version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
      - pwd
      - ls -l
      - cd target
      - ls -l
artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes
